CREATE TABLE "GCG_3057_BAL_CORR"(
 "EMPLOYEE" CHAR(5) NOT NULL ,
 "BAL_DATE" DATE NOT NULL ,
 "CORR_REQUEST_BY" CHAR(8),
 "CORRECTION" BIT NOT NULL ,
 "APPROVED_BY" CHAR(8),
 "APPROVAL_DATE" DATE,
 "LAST_CORRECTION_DATE" DATE);